using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace System.CMD.NirCMD
{
    public static class Ext_String_
    {
public static string MousBtnLeft(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.MousBtnLeft_str()).NR();
public static string MousBtnRight(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.MousBtnRight_str()).NR();
public static string MousBtnMiddle(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.MousBtnMiddle_str()).NR();
public static string Backspace(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Backspace_str()).NR();
public static string Tab(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Tab_str()).NR();
public static string Enter(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Enter_str()).NR();
public static string Shift(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Shift_str()).NR();
public static string Ctrl(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Ctrl_str()).NR();
public static string Alt(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Alt_str()).NR();
public static string Pause(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Pause_str()).NR();
public static string CapsLock(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.CapsLock_str()).NR();
public static string Escape(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Escape_str()).NR();
public static string Space(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Space_str()).NR();
public static string PageUp(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.PageUp_str()).NR();
public static string PageDown(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.PageDown_str()).NR();
public static string End(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.End_str()).NR();
public static string Home(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Home_str()).NR();
public static string Insert(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Insert_str()).NR();
public static string Delete(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Delete_str()).NR();
public static string Win(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Win_str()).NR();
public static string WinRight(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.WinRight_str()).NR();
public static string KeyApplication(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.KeyApplication_str()).NR();
public static string ScrollLock(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.ScrollLock_str()).NR();
public static string PrintScreen(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.PrintScreen_str()).NR();
public static string СommaPoint(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.СommaPoint_str()).NR();
public static string EQUally(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.EQUally_str()).NR();
public static string Сomma(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Сomma_str()).NR();
public static string Minus(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Minus_str()).NR();
public static string Dot(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Dot_str()).NR();
public static string Slash(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Slash_str()).NR();
public static string Tilda(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Tilda_str()).NR();
public static string SqueaBraketBegin(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.SqueaBraketBegin_str()).NR();
public static string UnSlash(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.UnSlash_str()).NR();
public static string SqueaBraketEnd(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.SqueaBraketEnd_str()).NR();
public static string MarkUno(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.MarkUno_str()).NR();
public static string ArrowLeft(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.ArrowLeft_str()).NR();
public static string ArrowUp(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.ArrowUp_str()).NR();
public static string ArrowRight(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.ArrowRight_str()).NR();
public static string ArrowDown(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.ArrowDown_str()).NR();
public static string _0(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._0_str()).NR();
public static string _1(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._1_str()).NR();
public static string _2(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._2_str()).NR();
public static string _3(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._3_str()).NR();
public static string _4(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._4_str()).NR();
public static string _5(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._5_str()).NR();
public static string _6(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._6_str()).NR();
public static string _7(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._7_str()).NR();
public static string _8(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._8_str()).NR();
public static string _9(this string _this) => _this.Add("nircmd sendkeypress ").Add(0._9_str()).NR();
public static string A(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.A_str()).NR();
public static string B(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.B_str()).NR();
public static string C(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.C_str()).NR();
public static string D(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.D_str()).NR();
public static string E(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.E_str()).NR();
public static string F(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F_str()).NR();
public static string G(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.G_str()).NR();
public static string H(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.H_str()).NR();
public static string I(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.I_str()).NR();
public static string J(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.J_str()).NR();
public static string K(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.K_str()).NR();
public static string L(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.L_str()).NR();
public static string M(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.M_str()).NR();
public static string N(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.N_str()).NR();
public static string O(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.O_str()).NR();
public static string P(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.P_str()).NR();
public static string Q(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Q_str()).NR();
public static string R(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.R_str()).NR();
public static string S(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.S_str()).NR();
public static string T(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.T_str()).NR();
public static string U(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.U_str()).NR();
public static string V(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.V_str()).NR();
public static string W(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.W_str()).NR();
public static string X(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.X_str()).NR();
public static string Y(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Y_str()).NR();
public static string Z(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.Z_str()).NR();
public static string NumPad0(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad0_str()).NR();
public static string NumPad1(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad1_str()).NR();
public static string NumPad2(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad2_str()).NR();
public static string NumPad3(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad3_str()).NR();
public static string NumPad4(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad4_str()).NR();
public static string NumPad5(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad5_str()).NR();
public static string NumPad6(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad6_str()).NR();
public static string NumPad7(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad7_str()).NR();
public static string NumPad8(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad8_str()).NR();
public static string NumPad9(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPad9_str()).NR();
public static string NumPadStar(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPadStar_str()).NR();
public static string NumPadPlas(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPadPlas_str()).NR();
public static string NumPadMinus(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPadMinus_str()).NR();
public static string NumPadDot(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPadDot_str()).NR();
public static string NumPadSlash(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumPadSlash_str()).NR();
public static string NumLock(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.NumLock_str()).NR();
public static string F1(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F1_str()).NR();
public static string F2(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F2_str()).NR();
public static string F3(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F3_str()).NR();
public static string F4(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F4_str()).NR();
public static string F5(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F5_str()).NR();
public static string F6(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F6_str()).NR();
public static string F7(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F7_str()).NR();
public static string F8(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F8_str()).NR();
public static string F9(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F9_str()).NR();
public static string F10(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F10_str()).NR();
public static string F11(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F11_str()).NR();
public static string F12(this string _this) => _this.Add("nircmd sendkeypress ").Add(0.F12_str()).NR();
    }
}
